### ISSUE TITLE
Hackathon tasks - 2

### ISSUE THREAD

**Issue by nponeccop** [nponeccop/HNC#97]
- [x] https://github.com/nponeccop/HNC/blob/master/HN/Optimizer/ClassyLattice.hs#L9 remove code duplication with `fromJoinFun`
- [x] https://github.com/nponeccop/HNC/blob/master/HN/Optimizer/ClassyLattice.hs#L22 code duplication with `mereJoin` (note also explicit exports may detect that something is unused)
- [x] https://github.com/nponeccop/HNC/blob/master/HN/Optimizer/GraphCompiler.hs#L27 use `liftA2` and/or recursion schemes
- [x] https://github.com/nponeccop/HNC/blob/master/HN/Optimizer/GraphCompiler.hs#L17 Extract common code from  two `foldr` in this module. They are sort of `concatMap`. 
- [x] https://github.com/nponeccop/HNC/blob/master/HN/Optimizer/GraphCompiler.hs#L35 think if `compileExpr` can be simplified
- [x] https://github.com/nponeccop/HNC/blob/master/HN/Optimizer/Inliner2.hs#L105 LambdaCase and `phi` inlining
- [x] https://github.com/nponeccop/HNC/blob/master/HN/Optimizer/SimpleAlias.hs#L28 extract common pattern of rewrite only applied to expression in `LetIn`. Find the same pattern elsewhere in `HN/Optimizer`
- [x] https://github.com/nponeccop/HNC/blob/master/CPP/BackendTools.hs#L12 use guards to use `cppType x` only once
- [x] https://github.com/nponeccop/HNC/blob/master/CPP/BackendTools.hs#L15 LambdaCase (same in `nonStaticReference`)
- [x] https://github.com/nponeccop/HNC/blob/master/CPP/TypeProducer.hs#L12 LambdaCase

**Comment by ingvar-lynn** [comment]
однако спам получился. да ещё и с гардами опять не вышло.

**Comment by nponeccop** [comment]
Норм, ща разберусь. Относись к этому как к учебному процессу.

**Comment by nponeccop** [comment]
Закоммитил только `mergeFacts`: b463d0506f339f8319b54075bf624a71b1187216

**Comment by ingvar-lynn** [comment]
с гардами тоже можно мержить, 3я попытка успешная.

**Comment by nponeccop** [comment]
4-я замержена :)

**Comment by nponeccop** [comment]
Оставшиеся таски переместил в #111
